app.py
from flask import Flask, render_template
from flask_cors import CORS
# import backend functions
from games.wedgedle.routes import wedgedle_bp
from games.shipdle.routes import shipdle_bp

app = Flask(__name__)
CORS(app)

app.register_blueprint(wedgedle_bp, url_prefix="/wedgedle")
app.register_blueprint(shipdle_bp, url_prefix="/shipdle")

@app.route("/")
def landing():
    return render_template("landing.html", game_name="wedgedle")

@app.route("/games/wedgedle")
def wedgedle():
    return render_template("wedgedle.html")

@app.route("/games/shipdle")
def shipdle():
    return render_template(
        "shipdle.html", 
        game_title="Y-Wingdle",
        game_name="shipdle"
    )


if __name__ == "__main__":
    # app.run(debug=True)
    # app.run(host="0.0.0.0", port=5000, debug=True)
    app.run()

games/shipdle/routes.py
from flask import jsonify, request, render_template, Blueprint, url_for
# import backend functions
from utils.reset_time import get_next_reset, get_server_now, get_today_date
from .shipdle import ShipdleGame

shipdle_bp = Blueprint("shipdle", __name__)
game = ShipdleGame()

# @shipdle_bp.route("/")
# def index():
#     return render_template("shipdle.html")

@shipdle_bp.route("api/shipdle/reset_time")
def reset_time():
    return { 
        "server_now": get_server_now().isoformat(),
        "reset_time": get_next_reset().isoformat()
    }

@shipdle_bp.route("api/start", methods=["POST"])
def start():
    mode = request.json["mode"]

    if mode == "unlimited":
        game_id = game.start_unlimited_game()
        result = {
            "game_id": game_id,
        }
    elif mode == "daily":
        game_id = get_today_date()
        result = {
            "game_id": game_id
        }
    
    return result

@shipdle_bp.route("api/shipdle/search")
def search():
    query = request.args.get("q", "").lower()
    result = game.search_ships(query)

    for ship in result:
        ship["image"] = url_for("static", filename=ship["image"], _external=False)

    return jsonify(result)

@shipdle_bp.route("api/shipdle/guess", methods=["POST"])
def guess():
    data = request.get_json()

    if "guess" not in data:
        return jsonify({"error": "Missing guess"}), 400
    
    result = game.check_guess(data["guess"], data["mode"], data["game_id"])
    img = result["guess_info"]["info"]["image"]
    result["guess_info"]["info"]["image"] = url_for("static", filename=img, _external=False)

    return jsonify(result)

@shipdle_bp.route("api/shipdle/answer", methods=["POST"])
def answer():
    data = request.get_json()

    ship = game.get_target(data["mode"], data["game_id"])

    return jsonify({
        "id": ship["id"],
        "name": ship["name"],
        "alignment": ship["alignment"],
        "image": url_for("static", filename=ship["image"], _external=False)
    })

@shipdle_bp.route("api/shipdle/images")
def images():
    imgs = game.get_images()
    return jsonify([
        url_for("static", filename=img)
        for img in imgs
    ])

# if __name__ == "__main__":
#     shipdle_bp.run(debug=True)

games/wedgedle/routes.py
from flask import jsonify, request, render_template, Blueprint, url_for
# import backend functions
from utils.reset_time import get_next_reset, get_server_now, get_today_date
from .wedgedle import WedgedleGame

wedgedle_bp = Blueprint("wedgedle", __name__)
game = WedgedleGame()

# @wedgedle_bp.route("/")
# def index():
#     return render_template("wedgedle.html")

@wedgedle_bp.route("api/wedgedle/reset_time")
def reset_time():
    return { 
        "server_now": get_server_now().isoformat(),
        "reset_time": get_next_reset().isoformat()
    }

@wedgedle_bp.route("api/start", methods=["POST"])
def start():
    mode = request.json["mode"]

    if mode == "unlimited":
        game_id = game.start_unlimited_game()
        result = {
            "game_id": game_id,
        }
    elif mode == "daily":
        game_id = get_today_date()
        result = {
            "game_id": game_id
        }
    
    return result

@wedgedle_bp.route("api/wedgedle/search")
def search():
    query = request.args.get("q", "").lower()
    result = game.search_characters(query)

    for char in result:
        char["image"] = url_for("static", filename=char["image"], _external=False)

    return jsonify(result)

@wedgedle_bp.route("api/wedgedle/guess", methods=["POST"])
def guess():
    data = request.get_json()

    if "guess" not in data:
        return jsonify({"error": "Missing guess"}), 400
    
    result = game.check_guess(data["guess"], data["mode"], data["game_id"])
    img = result["guess_info"]["info"]["image"]
    result["guess_info"]["info"]["image"] = url_for("static", filename=img, _external=False)

    return jsonify(result)

@wedgedle_bp.route("api/wedgedle/answer", methods=["POST"])
def answer():
    data = request.get_json()

    character = game.get_target(data["mode"], data["game_id"])

    return jsonify({
        "id": character["id"],
        "name": character["name"],
        "alignment": character["alignment"],
        "image": url_for("static", filename=character["image"], _external=False)
    })

@wedgedle_bp.route("api/wedgedle/images")
def images():
    imgs = game.get_images()
    return jsonify([
        url_for("static", filename=img)
        for img in imgs
    ])

# if __name__ == "__main__":
#     wedgedle_bp.run(debug=True)

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>{% block title %}Wedgedle{% endblock %}</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
    {% block extra_css %}{% endblock %}
  </head>

  <body data-game="{{ game_name | default('wedgedle') }}">
    
    {% block before_title %}{% endblock %}
    <h1 id="game-title" class="game-title">
      {{ game_title | default("Wedgedle") }}
    </h1>
    {% block after_title %}{% endblock %}

    <main class="content">
        {% block content %}{% endblock %}
    </main>

    {% block scripts %}{% endblock %}
  </body>
</html>
    

templates/landing.html
{% extends "base.html" %}

{% block extra_css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/landing.css') }}">
{% endblock %}


    {% block before_title %}
    <div id="game-info" class="game-info">
        <a href="https://discord.gg/gMCZNHBVc2" target="_blank" rel="noopener noreferrer" title="Join the Discord">
            <div id="discord-button" class="info-button btn">
                <img src="{{ url_for('static', filename='images/misc/discord.png') }}">
            </div>
        </a>
        <!-- <button id="reddit-button" class="info-button btn"> -->
            <!-- <img src="{{ url_for('static', filename='images/misc/reddit.png') }}"> -->
        <!-- </button> -->
        <!-- <button id="notes-button" class="info-button btn">?</button> -->
    </div>
    {% endblock %}
    

    {% block content %}
    <div class="game-grid">
        <a href="/games/wedgedle" class="game-square">
            <img src="{{ url_for('static', filename='images/wedge_antilles.webp') }}" alt="?" class="Light">
            <div class="game-square-desc">
                <h2 class="game-square-header">Wedge-dle</h2>
                <div class="game-square-text">Daily Character Guessing Game</div>
            </div>
        </a>
        <a href="/games/shipdle" class="game-square">
            <img src="{{ url_for('static', filename='images/ships/rebel-y-wing.png') }}" alt="?" class="Light">
            <div class="game-square-desc">
                <h2 class="game-square-header">Y-Wing-dle</h2>
                <div class="game-square-text">Daily Ship Guessing Game</div>
            </div>
        </a>
    </div>

    <div id="landing-intro" class="landing-intro">
        <h2 id="intro-header">New Updates</h2>
        <p id="intro-paragraph">
            Y-Wingdle is live! Test your knowledge of SWGOH ships in the new mode.<br>
            <br>UNLIMITED Mode is now available for both Wedgedle and Y-Wingdle. No more waiting for resets.<br>
            <br>Have any feedback or new ideas? Join the discord (link in top right).<br>
        </p>
    </div>

    {% endblock %}

    {% block scripts %}

    {% endblock %}

templates/shipdle.html
{% extends "base.html" %}

{% block extra_css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/shipdle.css') }}">
{% endblock %}

{% block before_title %}
  <a href="/" class="back-arrow btn">←</a>
  <div id="game-info" class="game-info">
    <div id="mode-switch" class="mode-switch">
      <label id="mode-switcher" class="switch">
        <input id="change-mode-btn" type="checkbox">
        <span class="slider"></span>
      </label>
      <div id="mode-text" class="mode-text">unlimited</div>
    </div>
    <button id="help-button" class="info-button btn">?</button>
  </div>
{% endblock %}

{% block content %}
    <div id="give-up-btn" class="give-up-btn btn">give up</div>
    <div class="input-wrapper">
      <div id="input-elems" class="input-elems">
        <div id="input-border" class="input-border">
            <input id="guess-input" class="guess-input" type="text" placeholder="Enter character name"/>
          <button id="guess-button" class="guess-button btn">>>></button>
        </div>
        
        <div id="guess-list" class="guess-list hidden"></div>
      </div>
    </div>
    
    <div id="game-container">
      <div id="cat-list" class="header-row">
        <div class="header-box">Ship</div>
        <div class="header-box">Alignment</div>
        <div class="header-box">Crew Members</div>
        <div class="header-box">Faction(s)</div>
        <div class="header-box">Release Year</div>
        <div class="header-box">Role</div>
      </div>

      <div id="guess-container"></div>
    </div>

    <!-- Win Loss Overlay -->
    <div id="endgame-overlay" class="modal-overlay hidden">
      <div id="endgame-modal" class="modal">
        <button id="endgame-close-btn" class="close-btn btn">✕</button>
        <h2 id="endgame-title" class="endgame-title"></h2>
        <div id="endgame-guess-cnt" class="endgame-msg"></div>
        <div id="endgame-answer"></div>
        <div class="reset-timer-wrapper">
          <div class="reset-timer-text">Next Ship in:</div>
          <div id="end-timer" class="reset-timer"></div>
        </div>
      </div>
    </div>

    <!-- Help Information -->
    <div id="help-overlay" class="modal-overlay hidden">
      <div id="help-modal" class="modal">
        <button id="help-close-btn" class="close-btn btn">✕</button>

        <h3 id="help-title" class="help-header">How to play</h3>
        <p id="help-description" class="help-desc"></p>
        
        <div class="reset-timer-wrapper">
          <div class="reset-timer-text">Next Ship in:</div>
          <div id="help-timer" class="reset-timer"></div>
        </div>
        
        <h4 id="help-properties" class="help-header">Properties</h4>
        <div class="modal-subsect">
          <div id="help-subtext"></div>
        </div>
        
        <div id="help-feedback" class="help-header">Feedback</div>
          <div id="help-color-grid">
            <div class="help-color-square">
              <div class="help-color-example correct"></div>
              <div class="help-color-desc">correct</div>
            </div>
            
            <div class="help-color-square">
              <div class="help-color-example partial"></div>
              <div class="help-color-desc">partial</div>
            </div>
            
            <div class="help-color-square">
              <div class="help-color-example incorrect"></div>
              <div class="help-color-desc">incorrect</div>
            </div>
          </div>
        <div class="modal-subsect">
          <div id="feedback-subtext"></div>
        </div>
      </div>
    </div>

{% endblock %}

{% block scripts %}
    <script>
    const START_URL = "{{ url_for('shipdle.start') }}";
    const GUESS_URL = "{{ url_for('shipdle.guess') }}";
    const SEARCH_URL = "{{ url_for('shipdle.search') }}";
    const ANSWER_URL = "{{ url_for('shipdle.answer') }}";
    const IMAGE_URL = "{{ url_for('shipdle.images') }}";
    const TIMER_URL = "{{ url_for('shipdle.reset_time') }}";
    </script>

    <script src="{{ url_for('static', filename='js/shipdle.js') }}"></script>
{% endblock %}

templates/wedgedle.html
{% extends "base.html" %}

{% block extra_css %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/wedgedle.css') }}">
{% endblock %}


    {% block before_title %}
    <a href="/" class="back-arrow btn">←</a>
    <div id="game-info" class="game-info">
      <div id="mode-switch" class="mode-switch">
        <label id="mode-switcher" class="switch">
          <input id="change-mode-btn" type="checkbox">
          <span class="slider"></span>
        </label>
        <div id="mode-text" class="mode-text">unlimited</div>
      </div>
      <button id="help-button" class="info-button btn">?</button>
    </div>
    {% endblock %}
    

    {% block content %}
    <div id="give-up-btn" class="give-up-btn btn">give up</div>
    <div class="input-wrapper">
      <div id="input-elems" class="input-elems">
        <div id="input-border" class="input-border">
            <input id="guess-input" class="guess-input" type="text" placeholder="Enter character name"/>
          <button id="guess-button" class="guess-button btn">>>></button>
        </div>
        
        <div id="guess-list" class="guess-list hidden"></div>
      </div>
    </div>
    
    
    <div id="game-container">
      <div id="cat-list" class="header-row">
        <div class="header-box">Name</div>
        <div class="header-box">Alignment</div>
        <div class="header-box">Ship</div>
        <div class="header-box">Faction(s)</div>
        <div class="header-box">Leader</div>
        <div class="header-box">Release Year</div>
        <div class="header-box">Role</div>
      </div>

      <div id="guess-container"></div>
    </div>

    <!-- Win Loss Overlay -->
    <div id="endgame-overlay" class="modal-overlay hidden">
      <div id="endgame-modal" class="modal">
        <button id="endgame-close-btn" class="close-btn btn">✕</button>
        <h2 id="endgame-title" class="endgame-title"></h2>
        <div id="endgame-guess-cnt" class="endgame-msg"></div>
        <div id="endgame-answer"></div>
        <div class="reset-timer-wrapper">
          <div class="reset-timer-text">Next Character in:</div>
          <div id="end-timer" class="reset-timer"></div>
        </div>
      </div>
    </div>

    <!-- Help Information -->
    <div id="help-overlay" class="modal-overlay hidden">
      <div id="help-modal" class="modal">
        <button id="help-close-btn" class="close-btn btn">✕</button>

        <h3 id="help-title" class="help-header">How to play</h3>
        <p id="help-description" class="help-desc"></p>
        
        <div class="reset-timer-wrapper">
          <div class="reset-timer-text">Next Character in:</div>
          <div id="help-timer" class="reset-timer"></div>
        </div>
        
        <h4 id="help-properties" class="help-header">Properties</h4>
        <div class="modal-subsect">
          <div id="help-subtext"></div>
        </div>

        <div id="help-feedback" class="help-header">Feedback</div>
        <div id="help-color-grid">
          <div class="help-color-square">
            <div class="help-color-example correct"></div>
            <div class="help-color-desc">correct</div>
          </div>
          
          <div class="help-color-square">
            <div class="help-color-example partial"></div>
            <div class="help-color-desc">partial</div>
          </div>
          
          <div class="help-color-square">
            <div class="help-color-example incorrect"></div>
            <div class="help-color-desc">incorrect</div>
          </div>
        </div>
        <div class="modal-subsect">
          <div id="feedback-subtext"></div>
        </div>
      </div>
    </div>

    {% endblock %}

    {% block scripts %}
    <script>
      const START_URL = "{{ url_for('wedgedle.start') }}";
      const GUESS_URL = "{{ url_for('wedgedle.guess') }}";
      const SEARCH_URL = "{{ url_for('wedgedle.search') }}";
      const ANSWER_URL = "{{ url_for('wedgedle.answer') }}";
      const IMAGE_URL = "{{ url_for('wedgedle.images') }}";
      const TIMER_URL = "{{ url_for('wedgedle.reset_time') }}";
    </script>
    <script src="{{ url_for('static', filename='js/wedgedle.js') }}"></script>
    {% endblock %}

templates/wedgedle_index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Wedgedle</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/wedgedle_styles.css') }}">
    <!-- <link href="https://fonts.cdnfonts.com/css/star-wars" rel="stylesheet"> -->
  </head>

  <body>
    <div id="game-info">
      <button id="help-button" class="btn">?</button>
    </div>
    <h1 id="game-title">Wedgedle</h1>
    

    <div class="input-wrapper">
      <div id="input-elems">
        <div id="input-border">
            <input id="guess-input" type="text" placeholder="Enter character name"/>
          <button id="guess-button" class="btn">>>></button>
        </div>
        
        <div id="guess-list" class="hidden"></div>
      </div>
    </div>
    
    <div id="game-container">
      <div id="cat-list" class="header-row hidden">
        <div class="header-box">Name</div>
        <div class="header-box">Alignment</div>
        <div class="header-box">Ship</div>
        <div class="header-box">Release Era</div>
        <div class="header-box">Faction(s)</div>
        <div class="header-box">Leader</div>
        <div class="header-box">Role</div>
      </div>

      <div id="guess-container"></div>
    </div>

    <!-- Win Loss Overlay -->
    <div id="endgame-overlay" class="hidden">
      <div id="endgame-modal">
        <button id="endgame-close-btn" class="btn">✕</button>
        <h2 id="endgame-title"></h2>
        <div id="endgame-guess-cnt" class="endgame-msg"></div>
        <div id="endgame-answer"></div>
        <div class="reset-timer-wrapper">
          <div class="reset-timer-text">Next Character in:</div>
          <div id="end-timer" class="reset-timer"></div>
        </div>
      </div>
    </div>

    <!-- Help Information -->
    <div id="help-overlay" class="hidden">
      <div id="help-modal">
        <button id="help-close-btn" class="btn">✕</button>

        <h3 id="help-title" class="help-header">How to play</h3>
        <p id="help-description" class="help-desc"></p>
        
        <div class="reset-timer-wrapper">
          <div class="reset-timer-text">Next Character in:</div>
          <div id="help-timer" class="reset-timer"></div>
        </div>
        
        <h4 id="help-properties" class="help-header">Properties</h4>
        <div id="help-subtext"></div>

        <div id="help-feedback" class="help-header">Feedback</div>
        <div id="help-color-grid">
          <div class="help-color-square">
            <div class="help-color-example correct"></div>
            <div class="help-color-desc">Correct</div>
          </div>
          
          <div class="help-color-square">
            <div class="help-color-example partial"></div>
            <div class="help-color-desc">Partial</div>
          </div>
          
          <div class="help-color-square">
            <div class="help-color-example incorrect"></div>
            <div class="help-color-desc">Incorrect</div>
          </div>
        </div>
      </div>
    </div>

    <script>
      const GUESS_URL = "{{ url_for('wedgedle.guess') }}";
      const SEARCH_URL = "{{ url_for('wedgedle.search') }}";
      const ANSWER_URL = "{{ url_for('wedgedle.answer') }}";
      const IMAGE_URL = "{{ url_for('wedgedle.images') }}";

      const IMAGE_PRELOAD = "{{ url_for('static', filename='data/characters.json') }}";
    </script>
    <script src="{{ url_for('static', filename='js/wedgedle_script.js') }}"></script>

  </body>

</html>